version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgresdb
      POSTGRES_PASSWORD: postgresdb
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    restart: unless-stopped